name: Build and Deploy Observable Framework

on:
  push:
    branches: [main] # Adjust based on your primary branch name
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Observable Framework works well with Node 16+

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # Option 1: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The default output folder for Observable Framework projects
